changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
    authors:
      - dependabot
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
        - feat
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
        - bugfix
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔧 Refactoring
      labels:
        - refactor
        - refactoring
    - title: 🎨 Styling
      labels:
        - style
        - styling
    - title: ⚡ Performance
      labels:
        - performance
        - perf
    - title: 🧪 Testing
      labels:
        - test
        - testing
    - title: 🔨 Chore
      labels:
        - chore
        - maintenance
    - title: Other Changes
      labels:
        - "*"
