package dev.hyo.openiap.conformance

// Generated by packages/conformance/scripts/generate-behavior-ids.mjs
// Do not edit. Behavior ids are the versioned public contract; see
// packages/conformance/src/spec/behaviors.mjs.

object ConformanceBehaviors {
    const val SUITE_VERSION = "1.0.0"

    const val PRODUCTS_FETCH_RETURNS_REQUESTED_SKUS = "products.fetch-returns-requested-skus"
    const val PRODUCTS_FETCH_NORMALIZES_REQUIRED_FIELDS = "products.fetch-normalizes-required-fields"
    const val PRODUCTS_FETCH_EMPTY_SKU_LIST_IS_AN_ERROR = "products.fetch-empty-sku-list-is-an-error"
    const val PRODUCTS_FETCH_SEPARATES_IN_APP_AND_SUBSCRIPTION_TYPES = "products.fetch-separates-in-app-and-subscription-types"
    const val PURCHASES_REQUEST_EMITS_PURCHASE_UPDATED_ON_SUCCESS = "purchases.request-emits-purchase-updated-on-success"
    const val PURCHASES_REQUEST_EMITS_ERROR_ON_USER_CANCEL = "purchases.request-emits-error-on-user-cancel"
    const val PURCHASES_ALREADY_OWNED_SURFACES_ALREADY_OWNED_ERROR = "purchases.already-owned-surfaces-already-owned-error"
    const val PURCHASES_PENDING_PURCHASE_IS_NOT_DELIVERED_AS_PURCHASED = "purchases.pending-purchase-is-not-delivered-as-purchased"
    const val PURCHASES_UNKNOWN_SKU_SURFACES_SKU_NOT_FOUND = "purchases.unknown-sku-surfaces-sku-not-found"
    const val COMPLETION_FINISH_REMOVES_TRANSACTION_FROM_PENDING = "completion.finish-removes-transaction-from-pending"
    const val COMPLETION_FINISH_IS_IDEMPOTENT = "completion.finish-is-idempotent"
    const val COMPLETION_UNFINISHED_PURCHASE_REMAINS_AVAILABLE = "completion.unfinished-purchase-remains-available"
    const val RESTORATION_AVAILABLE_PURCHASES_RETURNS_OWNED_ITEMS = "restoration.available-purchases-returns-owned-items"
    const val RESTORATION_AVAILABLE_PURCHASES_EXCLUDES_CONSUMED_ITEMS = "restoration.available-purchases-excludes-consumed-items"
    const val RESTORATION_AVAILABLE_PURCHASES_IS_EMPTY_FOR_NEW_USER = "restoration.available-purchases-is-empty-for-new-user"
    const val SUBSCRIPTIONS_ACTIVE_SUBSCRIPTION_IS_REPORTED_ACTIVE = "subscriptions.active-subscription-is-reported-active"
    const val SUBSCRIPTIONS_PENDING_SUBSCRIPTION_IS_NOT_ACTIVE = "subscriptions.pending-subscription-is-not-active"
    const val SUBSCRIPTIONS_UNKNOWN_STATE_SUBSCRIPTION_IS_NOT_ACTIVE = "subscriptions.unknown-state-subscription-is-not-active"
    const val SUBSCRIPTIONS_GROUPS_KEEP_INDEPENDENT_IDENTIFIERS = "subscriptions.groups-keep-independent-identifiers"
    const val SUBSCRIPTIONS_HAS_ACTIVE_AGREES_WITH_GET_ACTIVE = "subscriptions.has-active-agrees-with-get-active"
    const val LIFECYCLE_PURCHASE_STARTS_ACTIVE_ENTITLEMENT = "lifecycle.purchase-starts-active-entitlement"
    const val LIFECYCLE_EXPIRY_ENDS_ENTITLEMENT = "lifecycle.expiry-ends-entitlement"
    const val LIFECYCLE_GRACE_PERIOD_RETAINS_ENTITLEMENT = "lifecycle.grace-period-retains-entitlement"
    const val LIFECYCLE_BILLING_RETRY_SUSPENDS_ENTITLEMENT = "lifecycle.billing-retry-suspends-entitlement"
    const val LIFECYCLE_REFUND_ENDS_ENTITLEMENT = "lifecycle.refund-ends-entitlement"
    const val LIFECYCLE_REVOKE_ENDS_ENTITLEMENT = "lifecycle.revoke-ends-entitlement"
    const val LIFECYCLE_CANCEL_RETAINS_ENTITLEMENT_UNTIL_EXPIRY = "lifecycle.cancel-retains-entitlement-until-expiry"
    const val ERRORS_STORE_CODES_NORMALIZE_TO_SPEC_ERROR_CODES = "errors.store-codes-normalize-to-spec-error-codes"
    const val ERRORS_UNRECOGNIZED_STORE_CODE_NORMALIZES_TO_UNKNOWN = "errors.unrecognized-store-code-normalizes-to-unknown"
    const val ERRORS_UNSUPPORTED_CODES_ARE_NOT_SYNTHESIZED = "errors.unsupported-codes-are-not-synthesized"
    const val VERIFICATION_RESULT_EXPOSES_UNIFORM_VALIDITY = "verification.result-exposes-uniform-validity"
    const val IDENTIFIERS_PURCHASE_CARRIES_A_CONCRETE_STORE = "identifiers.purchase-carries-a-concrete-store"
    const val IDENTIFIERS_PURCHASE_TOKEN_IS_STABLE_ACROSS_READS = "identifiers.purchase-token-is-stable-across-reads"
    const val CAPABILITIES_UNSUPPORTED_OPERATIONS_DEGRADE_PREDICTABLY = "capabilities.unsupported-operations-degrade-predictably"
    const val CAPABILITIES_DECLARED_CAPABILITIES_MATCH_THE_MATRIX = "capabilities.declared-capabilities-match-the-matrix"

    /** Capability level per store, from packages/gql/src/capability-matrix.mjs. */
    val CAPABILITY_MATRIX: Map<String, Map<String, String>> = mapOf(
        "pendingPurchases" to mapOf("Google" to "required", "Horizon" to "required", "Amazon" to "unsupported"),
        "subscriptionBillingIssue" to mapOf("Google" to "required", "Horizon" to "unsupported", "Amazon" to "unsupported"),
        "offerCodeRedemption" to mapOf("Google" to "required", "Horizon" to "unsupported", "Amazon" to "unsupported"),
    )
}
