import { readdirSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { Kind, parse } from "graphql";
import { describe, expect, it } from "vitest";

import { buildBundle } from "../scripts/build-bundle.mjs";
import { compileCommerceSchemas } from "../scripts/build-json-schemas.mjs";

const at = (path) => fileURLToPath(new URL(`../${path}`, import.meta.url));
const source = readFileSync(at("generated/commerce-protocol.graphql"), "utf8");
const ast = parse(source);
const packageJson = JSON.parse(readFileSync(at("package.json"), "utf8"));

const type = (name) =>
  ast.definitions.find(
    (node) =>
      "name" in node &&
      node.name?.value === name &&
      [
        Kind.OBJECT_TYPE_DEFINITION,
        Kind.SCALAR_TYPE_DEFINITION,
        Kind.ENUM_TYPE_DEFINITION,
      ].includes(node.kind),
  );

describe("the canonical GraphQL contract", () => {
  it("is assembled from the authored schema layers and not a served API", () => {
    expect(source).toContain("GENERATED by scripts/assemble-schema.mjs");
    expect(source).toContain("not a served API");
    expect(source).toContain(
      "Edit the schema/*.graphql layers, never this file",
    );
    // The layers are the authored source; the assembled single file stays at
    // its long-published path for consumers and docs links.
    expect(readdirSync(at("schema")).sort()).toEqual([
      "01-primitives.graphql",
      "02-commerce-event.graphql",
      "03-provider-capabilities.graphql",
      "04-store-event-mapping.graphql",
      "05-operations.graphql",
      "06-compiler-vocabulary.graphql",
      "07-protocol-metadata.graphql",
    ]);
    expect(packageJson.exports["./commerce-protocol.graphql"]).toBe(
      "./generated/commerce-protocol.graphql",
    );
    expect(packageJson.exports["./schema/*"]).toBe("./schema/*");
  });

  it("physically isolates generated artifacts from authored review surfaces", () => {
    expect(packageJson.exports["./schemas/*"]).toBeUndefined();
    expect(packageJson.exports["./generated/schemas/*"]).toBe(
      "./generated/schemas/*",
    );
    expect(packageJson.exports["./generated/vectors/*"]).toBe(
      "./generated/vectors/*",
    );
    expect(packageJson.exports["./generated/bindings/*"]).toBe(
      "./generated/bindings/*",
    );
    expect(packageJson.exports["./generated/openapi/*"]).toBe(
      "./generated/openapi/*",
    );
    expect(packageJson.exports["./conformance"]).toEqual({
      types: "./conformance/index.d.ts",
      default: "./conformance/index.mjs",
    });
    // The mock provider imports `graphql`, which is a devDependency: a public
    // subpath would break in a consumer install. It stays test-internal.
    expect(packageJson.exports["./conformance/mock-provider"]).toBeUndefined();
    expect(packageJson.dependencies).toBeUndefined();
    expect(readdirSync(at("vectors")).sort()).toEqual(["signatures.json"]);
    expect(readdirSync(at("generated/vectors")).sort()).toEqual([
      "lifecycle.json",
      "operations.json",
    ]);
    expect(readdirSync(at("generated/bindings")).sort()).toEqual([
      "graphql-operations.json",
      "http-binding.json",
      "introspection-signature.json",
      "operations-sdl.json",
      "operations.graphql",
    ]);
    expect(readdirSync(at("generated/openapi")).sort()).toEqual([
      "commerce-protocol.openapi.json",
    ]);
    expect(readdirSync(at("generated/schemas")).sort()).toEqual([
      "commerce-event.schema.json",
      "commerce-protocol.bundle.schema.json",
      "operations.schema.json",
      "primitives.schema.json",
      "provider-capabilities.schema.json",
      "store-event-mapping.schema.json",
    ]);
  });

  it("defines the operation surface but never a stream root", () => {
    expect(
      ast.definitions.filter(
        (node) =>
          node.kind === Kind.OPERATION_DEFINITION ||
          node.kind === Kind.SCHEMA_DEFINITION,
      ),
    ).toEqual([]);
    // Query and Mutation are the operation containers; a Subscription root
    // would be a stream a shipped app could hold open, which the webhook
    // direction guardrail forbids.
    expect(type("Query")).toBeDefined();
    expect(type("Mutation")).toBeDefined();
    expect(type("Subscription")).toBeUndefined();
    const mutated = `${source}\ntype Subscription { events: CommerceEvent! }\n`;
    expect(() => compileCommerceSchemas(mutated)).toThrow(
      "Commerce Protocol SDL must not define a Subscription root",
    );
  });

  it("rejects executable roots on the metadata schema extension", () => {
    const mutated = `${source}\nextend schema { query: CommerceEvent }\n`;
    expect(() => compileCommerceSchemas(mutated)).toThrow(
      "Commerce Protocol SDL must not define executable roots on a schema extension",
    );
  });

  it("rejects a protocol version with a leading zero", () => {
    const mutated = source.replace('version: "1.0"', 'version: "01.0"');
    expect(mutated).not.toBe(source);
    expect(() => compileCommerceSchemas(mutated)).toThrow(
      "@protocol version must be canonical MAJOR.MINOR",
    );
  });

  it("derives the bundle identity from the protocol version", () => {
    const mutated = source.replace('version: "1.0"', 'version: "1.1"');
    expect(mutated).not.toBe(source);
    const generated = compileCommerceSchemas(mutated);
    const bundle = buildBundle({
      primitives: generated.get("primitives.schema.json"),
      event: generated.get("commerce-event.schema.json"),
      capabilities: generated.get("provider-capabilities.schema.json"),
      mapping: generated.get("store-event-mapping.schema.json"),
      operations: generated.get("operations.schema.json"),
    });
    expect(bundle.$id).toBe(
      "https://openiap.dev/schemas/commerce-protocol/1.1/commerce-protocol.bundle.schema.json",
    );
    expect(bundle.title).toContain("Protocol 1.1");
  });

  it("declares every compiler directive it uses", () => {
    const declared = new Set(
      ast.definitions
        .filter((node) => node.kind === Kind.DIRECTIVE_DEFINITION)
        .map((node) => node.name.value),
    );
    const used = new Set();
    for (const node of ast.definitions) {
      for (const entry of node.directives ?? []) used.add(entry.name.value);
      for (const field of node.fields ?? []) {
        for (const entry of field.directives ?? []) used.add(entry.name.value);
      }
    }
    expect([...used].filter((name) => !declared.has(name))).toEqual([]);
  });

  it("generates every committed modular schema without structural drift", () => {
    const generated = compileCommerceSchemas(source);
    for (const [name, schema] of generated) {
      const committed = JSON.parse(
        readFileSync(at(`generated/schemas/${name}`), "utf8"),
      );
      expect(schema, name).toEqual(committed);
    }
  });

  it("keeps every event envelope member in the SDL", () => {
    const event = JSON.parse(
      readFileSync(at("generated/schemas/commerce-event.schema.json"), "utf8"),
    );
    const fields = new Set(
      type("CommerceEvent").fields.map((field) => field.name.value),
    );
    expect([...fields].sort()).toEqual(Object.keys(event.properties).sort());
  });

  it("keeps known event values on the open scalar", () => {
    const event = JSON.parse(
      readFileSync(at("generated/schemas/commerce-event.schema.json"), "utf8"),
    );
    for (const value of event.properties.eventType.examples) {
      expect(source).toContain(`"${value}"`);
    }
    expect(type("CommerceEventType").kind).toBe(Kind.SCALAR_TYPE_DEFINITION);
  });

  it("makes omission explicit instead of conflating it with null", () => {
    const mutated = source.replace(
      "applicationId: Identifier! @optional",
      "applicationId: Identifier!",
    );
    expect(mutated).not.toBe(source);
    const event = compileCommerceSchemas(mutated).get(
      "commerce-event.schema.json",
    );
    expect(event.required).toContain("applicationId");
    expect(event.properties.applicationId).not.toHaveProperty("anyOf");
  });

  it("fails when an object leaves its open/closed wire policy implicit", () => {
    const mutated = source.replace(
      "type CommerceEvent\n  @jsonObject(additionalProperties: true)",
      "type CommerceEvent",
    );
    expect(mutated).not.toBe(source);
    expect(() => compileCommerceSchemas(mutated)).toThrow(
      "CommerceEvent must declare @jsonObject",
    );
  });

  it("fails instead of silently ignoring an unknown compiler directive", () => {
    const mutated = source.replace(
      "type CommerceEvent\n  @jsonObject(additionalProperties: true)",
      "type CommerceEvent\n  @jsonObject(additionalProperties: true)\n  @forgotten",
    );
    expect(mutated).not.toBe(source);
    expect(() => compileCommerceSchemas(mutated)).toThrow(
      "Unsupported compiler directive: @forgotten",
    );
  });

  it("fails instead of silently ignoring an unsupported directive argument", () => {
    const mutated = source.replace(
      "applicationId: Identifier! @optional",
      "applicationId: Identifier! @optional(ignored: true)",
    );
    expect(mutated).not.toBe(source);
    expect(() => compileCommerceSchemas(mutated)).toThrow(
      "@optional has unsupported arguments: ignored",
    );
  });

  it("rejects an invariant that names an unknown event member", () => {
    const mutated = source.replace(
      'require: ["userId", "productId"]',
      'require: ["missingMember"]',
    );
    expect(mutated).not.toBe(source);
    expect(() => compileCommerceSchemas(mutated)).toThrow(
      "@eventInvariant requires unknown member missingMember",
    );
  });

  it("rejects an invariant that names an unknown subscription state", () => {
    const mutated = source.replace(
      'snapshotState: "Active"',
      'snapshotState: "MissingState"',
    );
    expect(mutated).not.toBe(source);
    expect(() => compileCommerceSchemas(mutated)).toThrow(
      "@eventInvariant names unknown state MissingState",
    );
  });

  it("validates the custom directive vocabulary as GraphQL SDL", () => {
    const mutated = source.replace(
      "directive @optional on FIELD_DEFINITION | INPUT_FIELD_DEFINITION",
      "",
    );
    expect(mutated).not.toBe(source);
    expect(() => compileCommerceSchemas(mutated)).toThrow(
      'Unknown directive "@optional"',
    );
  });

  it("keeps generated document names safe and predictable", () => {
    const mutated = source.replace(
      'name: "commerce-event"',
      'name: "../commerce-event"',
    );
    expect(mutated).not.toBe(source);
    expect(() => compileCommerceSchemas(mutated)).toThrow(
      "Invalid @document name: ../commerce-event",
    );
  });

  it("fails when a generated definition names a nonexistent document", () => {
    const mutated = source.replace(
      'scalar Store\n  @definition(schema: "primitives")',
      'scalar Store\n  @definition(schema: "primitive")',
    );
    expect(mutated).not.toBe(source);
    expect(() => compileCommerceSchemas(mutated)).toThrow(
      "Store references unknown document primitive",
    );
  });
});
