#!/usr/bin/env node
// Assembles the authored schema layers in schema/ into the single-file
// contract generated/commerce-protocol.graphql, in filename order. That single
// file is a build output (the package still exports it at
// ./commerce-protocol.graphql for consumers); the schema/ layers are what
// humans author and review.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const at = (p) => fileURLToPath(new URL(`../${p}`, import.meta.url));

const BANNER = `# GENERATED by scripts/assemble-schema.mjs from the schema/ directory.
# Edit the schema/*.graphql layers, never this file.
`;

export function assembleSchema() {
  const parts = readdirSync(at("schema"))
    .filter((name) => name.endsWith(".graphql"))
    .sort();
  if (parts.length === 0) throw new Error("schema/ has no .graphql layers");
  const body = parts
    .map((name) => readFileSync(at(`schema/${name}`), "utf8").trimEnd())
    .join("\n\n");
  return `${BANNER}\n${body}\n`;
}

function main() {
  const assembled = assembleSchema();
  const target = at("generated/commerce-protocol.graphql");
  if (process.argv.includes("--check")) {
    if (readFileSync(target, "utf8") !== assembled) {
      console.error(
        "generated/commerce-protocol.graphql is stale. Run: node scripts/assemble-schema.mjs",
      );
      process.exit(1);
    }
    console.log("assembled contract is current");
  } else {
    writeFileSync(target, assembled);
    console.log(`wrote ${target}`);
  }
}

if (
  process.argv[1] &&
  fileURLToPath(import.meta.url) === resolve(process.argv[1])
) {
  main();
}
