// Generated by scripts/sync-versions.sh from openiap-versions.json.
// Do not edit.

enum OpenIapGeneratedVersion {
    static let spec = "3.3.0"
    static let apple = "3.3.0"
    static let google = "3.4.0"
}
