// Generated by scripts/sync-versions.sh from openiap-versions.json.
// Do not edit.

enum OpenIapGeneratedVersion {
    static let clientProtocol = "0.1.0"
    static let apple = "3.6.0"
    static let google = "3.6.1"
}
