// Generated by packages/conformance/scripts/generate-behavior-ids.mjs
// Do not edit. Copied from packages/gql so the published package is
// self-contained; packages/gql remains the source of truth.

export const SPEC_VERSION = "3.2.0";

export const CAPABILITY_STORES = Object.freeze(["Apple","Google","Amazon","Horizon"]);

export const CAPABILITY_MATRIX = Object.freeze({
  "fetchProducts": {
    "Apple": "required",
    "Google": "required",
    "Amazon": "required",
    "Horizon": "required"
  },
  "requestPurchase": {
    "Apple": "required",
    "Google": "required",
    "Amazon": "required",
    "Horizon": "required"
  },
  "finishTransaction": {
    "Apple": "required",
    "Google": "required",
    "Amazon": "required",
    "Horizon": "required"
  },
  "getAvailablePurchases": {
    "Apple": "required",
    "Google": "required",
    "Amazon": "required",
    "Horizon": "required"
  },
  "getActiveSubscriptions": {
    "Apple": "required",
    "Google": "required",
    "Amazon": "required",
    "Horizon": "required"
  },
  "pendingPurchases": {
    "Apple": "required",
    "Google": "required",
    "Amazon": "required",
    "Horizon": "required"
  },
  "subscriptionBillingIssue": {
    "Apple": "required",
    "Google": "required",
    "Amazon": "unsupported",
    "Horizon": "unsupported"
  },
  "offerCodeRedemption": {
    "Apple": "required",
    "Google": "required",
    "Amazon": "unsupported",
    "Horizon": "unsupported"
  },
  "alreadyOwnedError": {
    "Apple": "unsupported",
    "Google": "required",
    "Amazon": "required",
    "Horizon": "required"
  },
  "billingServiceLifecycleErrors": {
    "Apple": "unsupported",
    "Google": "required",
    "Amazon": "required",
    "Horizon": "required"
  },
  "storeWebhookLifecycle": {
    "Apple": "required",
    "Google": "required",
    "Amazon": "optional",
    "Horizon": "unsupported"
  }
});

/** @returns {'required' | 'optional' | 'unsupported'} */
export function capabilityLevel(behavior, store) {
  const entry = CAPABILITY_MATRIX[behavior];
  if (!entry) throw new Error(`Unknown capability behavior: ${behavior}`);
  const level = entry[store];
  if (!level) throw new Error(`Capability ${behavior} has no entry for store ${store}`);
  return level;
}
