// Generated by packages/conformance/scripts/generate-behavior-ids.mjs. Do not edit.
public enum ProviderBehaviors {
    public static let suiteVersion = "4.0.0"
    public static let clientProtocolVersion = "0.2.0"
    public static let mapping = ["subscriptions.active-subscription-is-reported-active","subscriptions.pending-subscription-is-not-active","subscriptions.unknown-state-subscription-is-not-active","subscriptions.groups-keep-independent-identifiers","errors.store-codes-normalize-to-spec-error-codes","errors.unrecognized-store-code-normalizes-to-unknown","identifiers.purchase-carries-a-concrete-store","capabilities.declared-capabilities-match-the-matrix","capabilities.unsupported-operations-degrade-predictably"]
    public static let runtime = ["products.fetch-returns-requested-skus","purchases.request-emits-purchase-updated-on-success","restoration.available-purchases-returns-owned-items","identifiers.purchase-token-is-stable-across-reads","completion.finish-is-idempotent"]
    public static let capabilities: [String: String] = ["pendingPurchases": "purchases.pending-purchase-is-not-delivered-as-purchased", "subscriptionBillingIssue": "apple-provider.subscription-billing-issue", "offerCodeRedemption": "apple-provider.offer-code-redemption"]
    public static let officialCapabilities = ["pendingPurchases","subscriptionBillingIssue","offerCodeRedemption"]
}
